iutils-admin/src/main/java/cn/iutils/sys/entity/Config.java
package cn.iutils.sys.entity;

import cn.iutils.sys.entity.DataEntity;

/**
* 公共配置表
* @author iutils.cn
* @version 1.0
*/
public class Config extends DataEntity<Config>{

    private static final long serialVersionUID = 1L;

    private String sysName;//系统名称
    private String moduleName;//模块名称
    private String configName;//配置key
    private String configValue;//配置值

    public Config() {
        super();
    }
    public Config(String id){
        super(id);
    }

    public String getSysName(){
        return sysName;
    }

    public void setSysName(String sysName){
        this.sysName = sysName;
    }

    public String getModuleName(){
        return moduleName;
    }

    public void setModuleName(String moduleName){
        this.moduleName = moduleName;
    }

    public String getConfigName(){
        return configName;
    }

    public void setConfigName(String configName){
        this.configName = configName;
    }

    public String getConfigValue(){
        return configValue;
    }

    public void setConfigValue(String configValue){
        this.configValue = configValue;
    }

}

iutils-admin/src/main/java/cn/iutils/sys/entity/DataEntity.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;
import cn.iutils.common.utils.UserUtils;

import java.util.Date;

/**
 * 数据实体
 * Created by CC on 16/9/24.
 */
public abstract class DataEntity<T> extends BaseEntity<T> {

    private static final long serialVersionUID = 1L;

    private User user;//当前用户
    private User createUser;//创建人
    private User updateUser;//更新人

    public DataEntity() {
        this.status = STATUS_NORMAL;
    }

    public DataEntity(String id) {
        this();
        this.id = id;
    }


    /**
     * 插入之前执行方法，子类实现
     */
    public void preInsert() {
        User user = UserUtils.getLoginUser();
        if (user != null) {
            this.updateBy = user.getId();
            this.createBy = user.getId();
        }
        this.createDate = new Date();
        this.updateDate = new Date();
    }

    /**
     * 更新之前执行方法，子类实现
     */
    public void preUpdate() {
        User user = UserUtils.getLoginUser();
        if (user != null) {
            this.updateBy = user.getId();
        }
        this.updateDate = new Date();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public User getCreateUser() {
        return createUser;
    }

    public void setCreateUser(User createUser) {
        this.createUser = createUser;
    }

    public User getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(User updateUser) {
        this.updateUser = updateUser;
    }
}

iutils-admin/src/main/java/cn/iutils/sys/entity/MsgReceive.java
package cn.iutils.sys.entity;

import cn.iutils.sys.entity.DataEntity;

/**
* 消息接收表
* @author iutils.cn
* @version 1.0
*/
public class MsgReceive extends DataEntity<MsgReceive>{

    private static final long serialVersionUID = 1L;

    private String msgId;//消息编号

    private MsgSend msgSend;//消息主体

    public MsgReceive() {
        super();
    }
    public MsgReceive(String id){
        super(id);
    }

    public String getMsgId(){
        return msgId;
    }

    public void setMsgId(String msgId){
        this.msgId = msgId;
    }

    public MsgSend getMsgSend() {
        return msgSend;
    }

    public void setMsgSend(MsgSend msgSend) {
        this.msgSend = msgSend;
    }
}

iutils-admin/src/main/java/cn/iutils/sys/entity/Organization.java
package cn.iutils.sys.entity;

import cn.iutils.common.BaseEntity;

/**
 * 组织机构表
 * 
 * @author cc
 */
public class Organization extends DataEntity<Organization> {

	private static final long serialVersionUID = 1L;
	private String name; // 组织机构名称
	private String parentId; // 父编号
	private Organization organization;//上级机构
	private String parentIds; // 父编号列表
	private Boolean available = Boolean.TRUE;

	public Organization() {
		super();
	}

	public Organization(String id) {
		super(id);
	}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentIds() {
        return parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Boolean getAvailable() {
		return available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}

	public boolean isRootNode() {
		return parentId.equals("0");
	}

}

iutils-admin/src/main/java/cn/iutils/sys/entity/Sessions.java
package cn.iutils.sys.entity;

/**
* session管理
* @author iutils.cn
* @version 1.0
*/
public class Sessions extends DataEntity<Sessions>{

    private static final long serialVersionUID = 1L;

    private String session;//session对象

    public Sessions() {
        super();
    }
    public Sessions(String id){
        super(id);
    }

    public String getSession(){
        return session;
    }

    public void setSession(String session){
        this.session = session;
    }

}

iutils-admin/src/main/java/cn/iutils/sys/entity/enums/DataScopeEnum.java
package cn.iutils.sys.entity.enums;

/**
 * 数据范围
 * @author cc
 */
public enum DataScopeEnum {

	all("所有数据"),orgFollow("所在机构及以下数据"), org("所在机构数据"),self("仅本人数据");

	private final String info;

	private DataScopeEnum(String info) {
		this.info = info;
	}

	public String getInfo() {
		return info;
	}

}

iutils-admin/src/main/java/cn/iutils/sys/controller/ConfigController.java
package cn.iutils.sys.controller;

import cn.iutils.common.utils.CacheUtils;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import cn.iutils.common.Page;
import cn.iutils.common.utils.JStringUtils;
import cn.iutils.common.BaseController;
import cn.iutils.sys.entity.Config;
import cn.iutils.sys.service.ConfigService;

/**
* 公共配置表 控制器
* @author iutils.cn
* @version 1.0
*/
@Controller
@RequestMapping("${adminPath}/sys/config")
public class ConfigController extends BaseController {

    @Autowired
    private ConfigService configService;

    @ModelAttribute
    public Config get(@RequestParam(required = false) String id) {
        Config entity = null;
        if (JStringUtils.isNotBlank(id)) {
            entity = configService.get(id);
        }
        if (entity == null) {
            entity = new Config();
        }
        return entity;
    }

    @RequiresPermissions("sys:config:view")
    @RequestMapping()
    public String list(Config config,Model model, Page<Config> page) {
        page.setEntity(config);
        model.addAttribute("page", page.setList(configService.findPage(page)));
        return "sys/config/list";
    }

    @RequiresPermissions("sys:config:create")
    @RequestMapping(value = "/create", method = RequestMethod.GET)
    public String create(Config config,Model model) {
        model.addAttribute("config", config);
        return "sys/config/form";
    }

    @RequiresPermissions("sys:config:create")
    @RequestMapping(value = "/create", method = RequestMethod.POST)
    public String create(Config config, RedirectAttributes redirectAttributes) {
        configService.save(config);
        addMessage(redirectAttributes,"新增成功");
        return "redirect:"+ adminPath +"/sys/config/update?id="+config.getId();
    }

    @RequiresPermissions("sys:config:update")
    @RequestMapping(value = "/update", method = RequestMethod.GET)
    public String update(Config config, Model model) {
        model.addAttribute("config", config);
        return "sys/config/form";
    }

    @RequiresPermissions("sys:config:update")
    @RequestMapping(value = "/update", method = RequestMethod.POST)
    public String update(Config config, RedirectAttributes redirectAttributes) {
        configService.save(config);
        CacheUtils.remove(config.getSysName() + config.getModuleName() + config.getConfigName());
        addMessage(redirectAttributes,"修改成功");
        return "redirect:"+ adminPath +"/sys/config/update?id="+config.getId();
    }

    @RequiresPermissions("sys:config:delete")
    @RequestMapping(value = "/{id}/delete", method = RequestMethod.GET)
    public String delete(@PathVariable("id") String id,int pageNo,int pageSize, RedirectAttributes redirectAttributes) {
        Config config = configService.get(id);
        configService.delete(config);
        CacheUtils.remove(config.getSysName()+config.getModuleName()+config.getConfigName());
        addMessage(redirectAttributes,"删除成功");
        return "redirect:"+ adminPath +"/sys/config?pageNo="+pageNo+"&pageSize="+pageSize;
    }
}

iutils-admin/src/main/java/cn/iutils/sys/controller/IndexController.java
package cn.iutils.sys.controller;

import java.util.List;
import java.util.Set;

import cn.iutils.common.utils.SystemUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import cn.iutils.common.BaseController;
import cn.iutils.sys.entity.Resource;
import cn.iutils.sys.service.ResourceService;
import cn.iutils.sys.service.UserService;

/**
 * 首页控制器
 * 
 * @author cc
 */
@Controller
@RequestMapping(value = "${adminPath}")
public class IndexController extends BaseController {

	@Autowired
	private ResourceService resourceService;

	@Autowired
	private UserService userService;

	@RequestMapping(method = RequestMethod.GET)
	public String index(Model model) {
		Set<String> permissions = userService.findPermissions();
		List<Resource> menus = resourceService.findMenus(permissions);
		model.addAttribute("menus", menus);
		return "index";
	}

	@RequestMapping(value = "/welcome", method = RequestMethod.GET)
	public String welcome(Model model) {
		model.addAttribute("systemInfo", SystemUtils.getSystemInfo());
		return "welcome";
	}

}

iutils-admin/src/main/java/cn/iutils/sys/controller/LogController.java
package cn.iutils.sys.controller;

import cn.iutils.common.datasource.DataSourceContextHolder;
import cn.iutils.common.datasource.DataSourceType;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import cn.iutils.common.Page;
import cn.iutils.common.BaseController;
import cn.iutils.common.utils.JStringUtils;
import cn.iutils.sys.entity.SLog;
import cn.iutils.sys.service.SLogService;

/**
 * 日志记录 控制器
 *
 * @author iutils
 * @version 1.0
 */
@Controller
@RequestMapping("${adminPath}/slog")
public class LogController extends BaseController {

    @Autowired
    private SLogService logService;

    @ModelAttribute
    public SLog get(@RequestParam(required = false) String id) {
        SLog entity = null;
        if (JStringUtils.isNotBlank(id)) {
            entity = logService.get(id);
        }
        if (entity == null) {
            entity = new SLog();
        }
        return entity;
    }

    /**
     * 查看日志列表
     *
     * @param model
     * @param page
     * @return
     */
    @RequiresPermissions("sys:slog:view")
    @RequestMapping()
    public String list(SLog sLog, Model model, Page<SLog> page) {
        page.setEntity(sLog);
        if(JStringUtils.isBlank(sLog.getOrderBy())){
            page.setOrderBy("a.create_date desc");
        }else{
            page.setOrderBy(sLog.getOrderBy());
        }
//        //切换数据源
//        DataSourceContextHolder.setDbType(DataSourceType.dataSource_2);
        model.addAttribute("page", page.setList(logService.findPage(page)));
//        //清除数据源 使用默认数据源
//        DataSourceContextHolder.clearDbType();
        return "sys/log/list";
    }

    /**
     * 查看日志详细
     *
     * @param log
     * @param model
     * @return
     */
    @RequiresPermissions("sys:slog:view")
    @RequestMapping(value = "/update", method = RequestMethod.GET)
    public String update(SLog log, Model model) {
        model.addAttribute("log", log);
        return "sys/log/edit";
    }

    /**
     * 批量删除日志
     *
     * @param ids
     * @param redirectAttributes
     * @return
     */
    @RequiresPermissions("sys:slog:edit")
    @RequestMapping(value = "/delete", method = RequestMethod.GET)
    public String delete(String[] ids, int pageNo, int pageSize,
                         RedirectAttributes redirectAttributes) {
        logService.deleteAll(ids);
        addMessage(redirectAttributes, "删除成功");
        return "redirect:" + adminPath + "/slog?pageNo=" + pageNo + "&pageSize=" + pageSize;
    }

}

iutils-admin/src/main/java/cn/iutils/sys/controller/LoginController.java
package cn.iutils.sys.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import cn.iutils.common.ResultVo;
import cn.iutils.common.utils.UserUtils;
import cn.iutils.sys.entity.User;
import cn.iutils.sys.service.PasswordHelper;
import cn.iutils.sys.service.UserService;
import org.apache.shiro.authc.ExcessiveAttemptsException;
import org.apache.shiro.authc.IncorrectCredentialsException;
import org.apache.shiro.authc.LockedAccountException;
import org.apache.shiro.authc.UnknownAccountException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import cn.iutils.common.BaseController;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 登录控制器
 * 
 * @author cc
 */
@Controller
@RequestMapping(value = "${adminPath}")
public class LoginController extends BaseController {

	@Autowired
	UserService userService;

	@Autowired
	private PasswordHelper passwordHelper;

	/**
	 * 获取异步登录界面
	 * @param response
	 * @return
	 */
	@RequestMapping("/ajaxLogin")
	public String ajaxLogin(HttpServletResponse response){
		ResultVo resultVo = null;
		//获取用户登录信息 验证已登录，返回登录信息
		String userName = UserUtils.getLoginUserName();
		if(userName!=null){
			resultVo = new ResultVo(ResultVo.SUCCESS,"1","登录成功",null);
			return renderString(response,resultVo);
		}else{
			return "ajaxLogin";
		}
	}

	/**
	 * 登录处理
	 * @param request
	 * @param response
	 * @param model
	 * @return
	 */
	@RequestMapping("/login")
	public String login(HttpServletRequest request,HttpServletResponse response, Model model) {
		//ajax登录失败处理
		if ("XMLHttpRequest".equalsIgnoreCase(request.getHeader("X-Requested-With"))) {
			ResultVo resultVo = new ResultVo(ResultVo.FAILURE, "0", "登录失败", null);
			return renderString(response,resultVo);
		}
        //获取用户登录信息 验证已登录，跳转到管理页
        String userName = UserUtils.getLoginUserName();
        if(userName!=null){
            return "redirect:" + adminPath;
        }
		String exceptionClassName = (String) request
				.getAttribute("shiroLoginFailure");
		model.addAttribute("username", request.getParameter("username"));
		String error = null;
		if (UnknownAccountException.class.getName().equals(exceptionClassName)) {
			error = "用户名/密码错误";
		} else if (IncorrectCredentialsException.class.getName().equals(
				exceptionClassName)) {
			error = "用户名/密码错误";
		} else if (ExcessiveAttemptsException.class.getName().equals(
				exceptionClassName)) {
			error = "错误次数操作超过限制";
		} else if (LockedAccountException.class.getName().equals(
				exceptionClassName)) {
			error = "帐号被锁定";
		}else if("jCaptcha.error".equals(exceptionClassName)) {
			error = "验证码错误";
		} else if (exceptionClassName != null) {
			error = "未知的错误";
		}
		model.addAttribute("msg", error);
		if (request.getParameter("forceLogout") != null) {
			error = "您已经被管理员强制退出，请重新登录";
			model.addAttribute("msg", error);
		}
		return "login";
	}

	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String register(){
		return "register";
	}

	/**
	 * 用户注册
	 * @param username 用户名
	 * @param password 密码
	 * @param password 确认密码
	 * @return
	 */
	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String register(String username,String password,String rpassword,Model model){
		String url = "register";
		//判断是否密码重复
		if(!password.equals(rpassword)){
			addMessage(model,"两次密码不一致");
		}else{
			User user = userService.getUserByUserName(username);
			if(user==null){
				user = new User();
				user.setUsername(username);
				user.setPassword(password);
				user.setOrganizationId("1");
				user.setRoleIdsStr("3,");
				passwordHelper.encryptPassword(user);
				userService.save(user);
				addMessage(model,"注册成功");
				url = "login";
			}else{
				addMessage(model,"账号已存在");
			}
		}
		return url;
	}

}

iutils-admin/src/main/webapp/WEB-INF/view/mobile/sys/organization/edit.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/view/include/taglib.jsp"%>
<html>
<head>
	<title>组织机构编辑</title>
	<%@ include file="../../include/head.jsp"%>
	<link rel="stylesheet" href="${ctxStatic}/3rd-lib/jquery-ztree/css/zTreeStyle.css">
	<style type="text/css">
		ul.ztree {
			margin-top: 10px;
			border: 1px solid #ddd;
			background: #fff;
			width: 198px;
			height: 200px;
			overflow-y: auto;
			overflow-x: auto;
		}
		.tpl-content-wrapper{margin-left:0}
	</style>
</head>
<body>
<script src="${ctxStatic}/assets/js/theme.js"></script>
<div class="am-g tpl-g">
	<!-- 内容区域 -->
	<div class="tpl-content-wrapper">
		<div class="row-content am-cf">
			<div class="row">
				<div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
					<div class="widget am-cf">
						<div class="widget-head am-cf">
							<div class="widget-title am-fl">机构编辑</div>
						</div>
						<div class="widget-body am-fr">
							<form class="am-form tpl-form-border-form" data-am-validator modelAttribute="organization" action="${ctx}/organization/update" method="post">
								<input type="hidden" name="id" value="${organization.id}" />
								<div class="am-form-group">
									<label class="am-u-sm-12 am-form-label am-text-left"><span class="error">*</span>上级机构：</label>
									<div class="am-u-sm-12">
										<div class="am-input-group" style="width: 200px;">
											<input type="text" id="parentName" class="am-form-field" value="${organization.organization.name}" required readonly/>
											<input type="hidden" id="parentId" name="parentId" value="${organization.parentId}" />
											<input type="hidden" id="parentIds" name="parentIds" value="${organization.parentIds}" />
								    <span class="am-input-group-btn">
									<button class="am-btn am-btn-default" id="menuBtn" type="button">选择</button>
								    </span>
										</div>
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-12 am-form-label am-text-left"><span class="error">*</span>机构名称：</label>
									<div class="am-u-sm-12">
										<input type="text" minlength="2" name="name" placeholder="机构名称（至少2个字符）" value="${organization.name}" required />
									</div>
								</div>
								<div class="am-form-group">
									<label class="am-u-sm-12 am-form-label am-text-left">是否可用：</label>
									<div class="am-u-sm-12">
										<select name="available" data="${organization.available}">
											<option value="true">可用</option>
											<option value="false">禁用</option>
										</select>
									</div>
								</div>
								<div class="am-form-group">
									<div class="am-u-sm-12">
										<shiro:hasPermission name="sys:organization:edit"><button type="submit" class="am-btn am-btn-primary">保存</button></shiro:hasPermission>
										<button type="button" class="am-btn am-btn-danger" onclick="closeModel(false)">关闭</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="menuContent" class="menuContent" style="display:none; position: absolute;z-index: 10000;">
	<ul id="tree" class="ztree" style="margin-top:0;"></ul>
</div>
<%@ include file="../../include/bottom.jsp"%>
<script src="${ctxStatic}/3rd-lib/jquery-ztree/js/jquery.ztree.core-3.5.min.js"></script>
<script src="${ctxStatic}/custom/js/ztree.select.js"></script>
<script type="text/javascript">
	$(function () {
		//消息提醒
		var msg = '${msg}';
		if(msg!=''){
			showMsg(msg);
			closeModel(true);//关闭窗口
		}
		initSelectValue(true);//初始化下拉框的值

		var zNodes =[
			<c:forEach items="${organizationList}" var="o" varStatus="status">
			{ id:${o.id}, pId:${o.parentId},pIds:'${o.parentIds}', name:'${o.name}', open:${o.rootNode}}<c:if test="${!status.last}">,</c:if>
			</c:forEach>
		];
		$.fn.ztreeSelect($("#tree"),zNodes);
	});
	//ztree点击回调
	function ztreeOnClickCall(treeNode){
		$("#parentId").val(treeNode.id);
		$("#parentIds").val(treeNode.pIds+treeNode.id+"/");
	}
</script>
</body>
</html>

iutils-admin/src/main/webapp/WEB-INF/view/mobile/sys/organization/list.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ include file="/WEB-INF/view/include/taglib.jsp"%>
<html>
<head>
   <title>组织机构列表</title>
   <%@ include file="../../include/head.jsp"%>
    <link rel="stylesheet" href="${ctxStatic}/3rd-lib/jquery-ztree/css/zTreeStyle.css">
    <style type="text/css">
        .tpl-content-wrapper{margin-left:0}
    </style>
</head>
<body>
<script src="${ctxStatic}/assets/js/theme.js"></script>
<div class="am-g tpl-g">
    <!-- 内容区域 -->
    <div class="tpl-content-wrapper">
        <div class="row-content am-cf">
            <div class="row">
                <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                    <div class="widget am-cf">
                        <div class="widget-head am-cf">
                            <div class="widget-title am-fl">组织机构树</div>
                        </div>
                        <div class="widget-body widget-body-lg am-fr">
                            <div class="am-scrollable-horizontal">
                                <ul id="tree" class="ztree"></ul><!-- 组织机构树 -->
                            </div>
                        </div>
                    </div>
                </div>

                <div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
                    <div class="widget am-cf">
                        <div class="widget-head am-cf">
                            <div class="widget-title am-fl">组织结构列表</div>
                        </div>
                        <div class="widget-body am-fr">
                            <div class="am-u-sm-12 am-u-md-3 am-u-lg-3">
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <shiro:hasPermission name="sys:organization:edit">
                                            <button type="button" class="am-btn am-btn-default am-btn-success"
                                                    onclick="openModel(false,'${ctx}/organization/create?id=${page.entity.id}')"><span class="am-icon-plus"></span> 新增
                                            </button></shiro:hasPermission>
                                    </div>
                                </div>
                            </div>

                            <div class="am-u-sm-12 am-u-md-9 am-u-lg-9">
                                <form id="searchForm" action="${ctx}/organization" method="post" style="display: none;">
                                    <input name="id" value="${page.entity.id}" />
                                    <input id="pageNo" name="pageNo" type="hidden" value="${page.pageNo}"/>
                                    <input id="pageSize" name="pageSize" type="hidden" value="${page.pageSize}"/>
                                    <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">

                                    </div>
                                </form>
                            </div>

                            <div class="am-u-sm-12 am-scrollable-horizontal">
                                <table id="contentTable"  class="am-table am-table-compact am-text-nowrap tpl-table-black" width="100%">
                                    <thead>
                                    <tr>
                                        <th>序号</th>
                                        <th>归属机构</th>
                                        <th>机构名称</th>
                                        <th>是否可用</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <c:forEach items="${page.list}" var="org" varStatus="status">
                                        <tr>
                                            <td>${status.index+1}</td>
                                            <td>${org.organization.name}</td>
                                            <td>${org.name}</td>
                                            <td>${org.available?'<span class="am-badge am-badge-success am-radius">可用</span>':'<span class="am-badge am-badge-danger am-radius">禁用</span>'}</td>
                                            <td>
                                                <a href="javascript:;" onclick="openModel(false,'${ctx}/organization/update?id=${org.id}')" title="编辑"><span class="am-icon-pencil"></span></a> <a
                                                    href="${ctx}/organization/delete?id=${org.id}&pageNo=${page.pageNo}&pageSize=${page.pageSize}"
                                                    onclick="return confirm('确认要删除该条数据吗？', this.href)" title="删除"><span class="am-text-danger am-icon-trash-o"></span></a></td>
                                        </tr>
                                    </c:forEach>
                                    </tbody>
                                </table>
                            </div>

                            <div class="am-u-lg-12 am-cf">
                                <%@ include file="../../utils/pagination.jsp" %>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<%@ include file="../../include/bottom.jsp"%>
<script src="${ctxStatic}/3rd-lib/jquery-ztree/js/jquery.ztree.core-3.5.min.js"></script>
<script>
    $(function () {
        var setting = {
            data: {
                simpleData: {
                    enable: true
                }
            },
            callback : {
                onClick : function(event, treeId, treeNode) {
                    location.href = "${ctx}/organization?id="+treeNode.id;
                }
            }
        };
        var zNodes =[
            <c:forEach items="${organizationList}" var="o" varStatus="status">
            { id:${o.id}, pId:${o.parentId}, name:"${o.name}", open:${o.rootNode}}<c:if test="${!status.last}">,</c:if>
            </c:forEach>
        ];
        $(document).ready(function(){
            var ztree = $.fn.zTree.init($("#tree"), setting, zNodes);
            ztree.expandAll(true);
        });
    });
</script>
<script>
  $(document).ready(function () {
      var msg = '${msg}';
      if(msg!=''){
          showMsg(msg);
      }
  });
</script>
</body>
</html>